# environment setup
language: swift
osx_image: xcode11.1

# caching of dependencies
cache:
  bundler: true
  
branches:
  only:
    - master
    - develop
    - /^release\/.*$/

# prepare dependency managers
before_install:
  - brew update
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"

# install dependencies
install:
  - bundle install

# jobs and stages to run
jobs:
  include:
    - stage: "Code validation"
      name: "Code validation"
      script:
        - bundle exec danger
    - stage: "Test"
      name: "Unit tests"
      script:
        - bundle exec fastlane unit_test
    - stage: "Deploy"
      name: "Deploy to App Store"
      script:
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane deploy_to_app_store
      if: branch =~ /^release\/.*$/
